# Generated by Django 4.1.1 on 2022-10-03 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.int_list_validator],
                    ),
                ),
                ("color", models.CharField(max_length=64)),
                ("points", models.IntegerField()),
                ("level", models.IntegerField()),
                ("isReserved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "game_url",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=8,
                        max_length=40,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("num_players", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Noble",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.int_list_validator],
                    ),
                ),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="splendor.game",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level", models.IntegerField(blank=True, null=True)),
                ("cards", models.ManyToManyField(blank=True, to="splendor.card")),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to="splendor.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck",
                        to="splendor.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cards", models.ManyToManyField(blank=True, to="splendor.card")),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board",
                        to="splendor.game",
                    ),
                ),
                ("nobles", models.ManyToManyField(blank=True, to="splendor.noble")),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gems",
                    models.CharField(
                        max_length=64,
                        validators=[django.core.validators.int_list_validator],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="splendor.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank",
                        to="splendor.player",
                    ),
                ),
            ],
        ),
    ]
