# Generated by Django 4.1.1 on 2022-10-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="id",
        ),
    ]
