# Generated by Django 4.1.1 on 2022-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0002_remove_game_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="num_players",
            field=models.IntegerField(default=1),
        ),
    ]
