# Generated by Django 4.1.1 on 2022-10-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0004_noble_game_noble_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="nobles",
        ),
        migrations.RemoveField(
            model_name="noble",
            name="game",
        ),
        migrations.AddField(
            model_name="noble",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nobles",
                to="splendor.board",
            ),
        ),
    ]
