# Generated by Django 4.1.1 on 2022-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0005_remove_board_nobles_remove_noble_game_noble_board"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noble",
            name="board",
        ),
        migrations.RemoveField(
            model_name="noble",
            name="player",
        ),
        migrations.AddField(
            model_name="board",
            name="nobles",
            field=models.ManyToManyField(blank=True, to="splendor.noble"),
        ),
    ]
