# Generated by Django 4.1.2 on 2022-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0006_remove_noble_board_remove_noble_player_board_nobles"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="color",
            field=models.IntegerField(),
        ),
    ]
