# Generated by Django 4.1.2 on 2022-10-14 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0008_player_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="game_turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_player",
                to="splendor.game",
            ),
        ),
    ]
