# Generated by Django 4.1.2 on 2022-10-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("splendor", "0009_player_game_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="turn",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
